// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsWthGOlpMjSqDDJ8eybXvQoyxd5FvG5E',
    appId: '1:804181704830:web:5e1da2b3f5f02ef8ca982f',
    messagingSenderId: '804181704830',
    projectId: 'agua-pwa-22618',
    authDomain: 'agua-pwa-22618.firebaseapp.com',
    storageBucket: 'agua-pwa-22618.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6nlJ_FnWRMwdjdvgPaLS_dmNaJN1SaVE',
    appId: '1:804181704830:android:0ce8080abe24ff68ca982f',
    messagingSenderId: '804181704830',
    projectId: 'agua-pwa-22618',
    storageBucket: 'agua-pwa-22618.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKBlqQmr0iCJntOm7sGNbrp8DlcMclwN4',
    appId: '1:804181704830:ios:522db0db2075bd69ca982f',
    messagingSenderId: '804181704830',
    projectId: 'agua-pwa-22618',
    storageBucket: 'agua-pwa-22618.firebasestorage.app',
    iosBundleId: 'com.example.aguaPwa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKBlqQmr0iCJntOm7sGNbrp8DlcMclwN4',
    appId: '1:804181704830:ios:522db0db2075bd69ca982f',
    messagingSenderId: '804181704830',
    projectId: 'agua-pwa-22618',
    storageBucket: 'agua-pwa-22618.firebasestorage.app',
    iosBundleId: 'com.example.aguaPwa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsWthGOlpMjSqDDJ8eybXvQoyxd5FvG5E',
    appId: '1:804181704830:web:8b141067b7c02b94ca982f',
    messagingSenderId: '804181704830',
    projectId: 'agua-pwa-22618',
    authDomain: 'agua-pwa-22618.firebaseapp.com',
    storageBucket: 'agua-pwa-22618.firebasestorage.app',
  );
}
